### ISSUE TITLE
Refactor popped/pushed by having them use a common Abstract Operation

### ISSUE THREAD

**Issue by rricard** [tc39/proposal-change-array-by-copy#19]
See comments in #18

**Comment by acutmore** [comment]
We no longer have `popped` and `pushed`. The 10 new methods have been reduced to 4.

We will likely need to re-review which parts of the new spec text would benefit from sharing a new AO, if any.

**Comment by acutmore** [comment]
re-looking over the 4-method spec. I'm going to close this (we can re-open if needed). Each method is slightly different in how it operates.

- toReversed : direct transfer from the original array to the copy, backwards
- toSorted : transfer to an internal spec list first, which is sorted, then transfer from the spec list to a new JS array
- toSpliced: does the more complex splice steps
- with: transfers from the original array to the copy, but with a conditional step doing something different on one index
