### ISSUE TITLE
popped, shifted, unshifted, pushed are likely redundant

### ISSUE THREAD

**Issue by benlesh** [tc39/proposal-change-array-by-copy#24]
- `popped` and `shifted` are basically variations on `slice`.
- `unshifted` and `pushed` are variations on `concat`.

This is the guy who works on RxJS telling you not to add too many redundant methods. (serious :pot: :kettle: 🖤 energy) It will only serve to create confusion. In _particular_ since they are so similarly named to existing APIs. I can already see the bugs slipping through code reviews.

**Comment by rricard** [comment]
Definitely a valid concern, this also relates to #10 and particularly the following comment: https://github.com/tc39-transfer/proposal-change-array-by-copy/issues/10#issuecomment-823512699

Just a dumb question: Would you think this remark also applies to Tuple that doesn't effectively has pop and push?

**Comment by rricard** [comment]
This also relates to #22 - Mozilla's concerns were that popped and pushed notably could be expected to be nonlinear time and therefore, it would maybe make more sense to not have them altogether.

**Comment by acutmore** [comment]
For completeness the variation `unshifted` and `pushed`  bring compared to `concat` is that they don't check [Symbol.isConcatSpreadable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/isConcatSpreadable).

(not saying this justifies their addition, just for anyone interested)

**Comment by benlesh** [comment]
> Just a dumb question: Would you think this remark also applies to Tuple that doesn't effectively has pop and push?

I assume you're talking about [this proposal](https://github.com/tc39/proposal-record-tuple)? Honestly, in all cases, (even `concat` to some degree).

Just with the additive ones, it's apparent what's more readable and flexible IMO.

```ts
const arr = [1, 2, 3];
const tuple = #['a', 'b'];

// Current idioms
const r1 = [...arr, 4];
const r2 = [0, ...arr];
const r3 = #['z', ...tuple];
const r4 = #[...tuple, 'c'];

// Proposed methods (FWIACT):

const r1 = arr.pushed(4);
const r2 = arr.unshifted(0);
const r3 = tuple.unshifted('z');
const r4 = tuple.pushed('c');
```

For the others... popped is easy:

```ts
const [first, ...rest] = arr;
const [a, ...smallerTuple] = tuple
```

And shifted is just `arr.slice(1)` or `tuple.slice(1)`, I think.

> For completeness the variation unshifted and pushed bring compared to concat is that they don't check Symbol.isConcatSpreadable.

Does seem to add an interesting wrinkle here. But still, in practice I feel like it's edge-casey enough that it's not worth proliferating more API around it. Just my two cents as a guy that desperately wants to reduce the API surface area of what *I'm* working on. 😅

**Comment by rricard** [comment]
Opened #27 to discuss this with the exact methods that could be removed. Will close this one as discussion should move there, thanks for suggesting!
