### ISSUE TITLE
The construction of return values should not use Symbol.species

### ISSUE THREAD

**Issue by acutmore** [tc39/proposal-change-array-by-copy#33]
The currently proposed spec text uses `ArraySpeciesCreate` to construct the returned Arrays.

There is a stage 1 proposal to reduce this type of subclass behaviour: https://github.com/tc39/proposal-rm-builtin-subclassing

**Comment by zloirock** [comment]
This proposal can't be accepted since it will break the web, https://github.com/tc39/proposal-rm-builtin-subclassing/issues/23
