### ISSUE TITLE
missing “filled"

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-change-array-by-copy#4]
I think these might be the only mutator methods not listed in the readme.

**Comment by zloirock** [comment]
For which use case?

**Comment by ljharb** [comment]
For any use case where you would use `.fill`. If we’re evaluating use cases, I’d object to including any form of splice on that basis.

**Comment by zloirock** [comment]
In this case, there also should be also `.copyWithin`, but I don't see any real-life use case.

`.fill` implies usage mainly for initialization of empty arrays or cleaning arrays and I don't see any real-life use case for `.filled`.

**Comment by ljharb** [comment]
Thanks, good catch.

Either we make non-mutating versions of every single one, no exceptions, or else we need to audit each one, and splice wouldn’t make the list since it’s confusing and slow.

 As for .filled, it can also be used to make a sparse array dense, not just for initialization.

**Comment by zloirock** [comment]
Sometimes I use `.slice` + `.splice` for short-form removing or adding elements of an array, `.spliced` just removes `.slice` here so for me it's a very useful method.

**Comment by rricard** [comment]
For the sake of consistency, we should add it both here and on Tuple...

**Comment by rricard** [comment]
Looking at `.copyWithin` with more distance now, I think it will be hard if we try to keep its current signature: `.copyWithin(target, start, end)` - we should open a separate issue on it...
