### ISSUE TITLE
Accept string index argument in `{Array, TypedArray}#withAt`

### ISSUE THREAD

**Issue by petamoriken** [tc39/proposal-change-array-by-copy#42]
I agree with the introduction of integer value checking in `{Array, TypedArray}#withAt`, which was not considered in `{Array, TypedArray}#at`. However, the current specification always throws a `RangeError` in the case of a string.

It's complicated, but I think we can avoid this problem by changing the specification as follows:

```js
let numericIndex;

if (typeof index === "string") {
  numericIndex = CanonicalNumericIndexString(index);
  if (numericIndex === undefined) {
    throw TypeError("Invalid index type");
  }

} else if (typeof index === "number") {
  numericIndex = index;

} else {
  throw TypeError("Invalid index type");
}

if (!IsIntegralNumber(numericIndex)) {
  throw RangeError("Invalid index");
}

// accept number -0
if (SameValue(numericIndex, -0)) {
  // IsValidIntegerIndex rejects -0, so overwrite it with 0
  numericIndex = 0;
}
```

**Comment by acutmore** [comment]
thanks for spotting this @petamoriken. I agree that we should align with the existing methods and accept string based index access.
This will be taken into account on the next round of updating the proposed spec.
