### ISSUE TITLE
Bogus length validation in Array.prototype.toSpliced

### ISSUE THREAD

**Issue by linusg** [tc39/proposal-change-array-by-copy#94]
[`Array.prototype.toSpliced`](https://tc39.es/proposal-change-array-by-copy/#sec-array.prototype.toSpliced) does this:

```
12. If newLen > 2^53 - 1, throw a TypeError exception.
13. Let A be ? ArrayCreate(𝔽(newLen)).
```

But [`ArrayCreate`](https://tc39.es/ecma262/#sec-arraycreate) does this:

```
1. If length > 2^32 - 1, throw a RangeError exception.
```

Couple of issues:

- Why is the length validated to be in a range much larger than the immediate next step allows in the first place?
- Why `TypeError` and not `RangeError` - this seems to be inherited from [`Array.prototype.splice`](https://tc39.es/ecma262/#sec-array.prototype.splice), which uses [`ArraySpeciesCreate`](https://tc39.es/ecma262/#sec-arrayspeciescreate) and only passes `actualDeleteCount` as the length in the next step however
- Is it intentional that depending on how much too large (i.e. above 2^32 - 1) the value is you'll get a different error type?

**Comment by acutmore** [comment]
Thanks for the question. Yes this is intentional, discussed in #54

**Comment by linusg** [comment]
Thanks!
